set(STREAMING_ALGORITHMS_VERSION x.y.z)

@PACKAGE_INIT@

set_and_check(STREAMING_ALGORITHMS_INCLUDE_DIR "@PACKAGE_CMAKE_INSTALL_INCLUDEDIR@")
set_and_check(STREAMING_ALGORITHMS_LIB_DIR "@PACKAGE_CMAKE_INSTALL_LIBDIR@")

FIND_LIBRARY(STREAMING_ALGORITHMS_LIBRARY NAMES streaming_algorithms PATHS ${STREAMING_ALGORITHMS_LIB_DIR})
set(STREAMING_ALGORITHMS_LIBRARIES ${STREAMING_ALGORITHMS_LIBRARY})
